export const metadata = {
  title: {
    en: "Startup Risk Scanner",
    ar: "ماسح مخاطر المشاريع الناشئة",
  },
  shortDescription: {
    en: "Identify your startup's biggest risks and get prioritized actions to reduce them.",
    ar: "اكتشف أكبر مخاطر مشروعك الناشئ واحصل على خطوات عملية مرتبة لتقليلها.",
  },
  longDescription: {
    en: "Understand what could prevent your startup from succeeding before you invest more time and money.",
    ar: "اعرف ما قد يمنع مشروعك من النجاح قبل استثمار المزيد من الوقت والمال.",
  },
  promise: {
    en: "Understand what could prevent your startup from succeeding before you invest more time and money.",
    ar: "اعرف ما قد يمنع مشروعك من النجاح قبل استثمار المزيد من الوقت والمال.",
  },
  categoryLabel: {
    en: "Business Validation",
    ar: "التحقق من الأعمال",
  },
  icon: "AlertTriangle",
  estimatedCompletionTime: "10 minutes",
  featured: true,
  availability: "active",
};

export const content = {
  en: {
    language: "en",
    direction: "ltr",
    header: {
      brand: "AI Source Hub",
      tagline: "Decision engines",
      navigationLabel: "Primary navigation",
      nav: [
        { label: "Home", href: "../../pages/Home/index.html" },
        { label: "Products", href: "../../pages/Home/index.html#products" },
        { label: "FAQ", href: "../../pages/Home/index.html#faq" },
      ],
    },
    footer: {
      brand: "AI Source Hub",
      version: "Startup Risk Scanner v1.0.0",
    },
    breadcrumbLabel: "Breadcrumb",
    homeLabel: "Home",
    homeHref: "../../pages/Home/index.html",
    eyebrow: "Business validation",
    title: metadata.title.en,
    description: metadata.shortDescription.en,
    promise: metadata.promise.en,
    formTitle: "Risk assessment",
    formDescription: "Answer quickly. Estimates are enough, and no confidential financial details are required.",
    buttonLabel: "Scan Startup Risks",
    processing: "Scanning risk profile...",
    progressLabel: "Assessment progress",
    emptyState: "Your risk report will appear here after the assessment.",
    states: {
      idle: "Complete the assessment to scan the startup risk profile.",
      input: "Keep answers practical and evidence-based.",
      invalid: "Some required inputs need attention.",
      success: "Risk scan complete.",
      partial: "Risk scan complete with limited confidence.",
      error: "The risk scan could not be completed. Please review the inputs.",
      reset: "Start a new assessment.",
    },
    labels: {
      overallRiskScore: "Overall Risk Score",
      riskLevel: "Risk Level",
      executiveSummary: "Executive Summary",
      riskBreakdown: "Risk Dimension Breakdown",
      topRisks: "Top Three Priority Risks",
      strongestArea: "Strongest Area",
      mostDangerousRisk: "Most Dangerous Risk",
      immediateNextAction: "Immediate Next Action",
      recommendations: "Prioritized Recommendations",
      validationPlan: "Recommended Validation Steps",
      disclaimer: "Important Disclaimer",
      restart: "Reassess",
      copyReport: "Copy Report",
      downloadReport: "Download Report",
      originalInputs: "Original Inputs",
    },
    levels: {
      low: "Low Risk",
      moderate: "Moderate Risk",
      high: "High Risk",
      critical: "Critical Risk",
    },
    priorities: {
      high: "High",
      medium: "Medium",
      low: "Low",
    },
    disclaimer:
      "This result is a decision-support assessment only. It is not financial, legal, investment, or professional advice and does not guarantee startup success.",
    report: {
      copied: "Report copied.",
      copyFailed: "Copy failed. Select and copy the report manually.",
    },
  },
  ar: {
    language: "ar",
    direction: "rtl",
    header: {
      brand: "AI Source Hub",
      tagline: "محركات قرار",
      navigationLabel: "التنقل الرئيسي",
      nav: [
        { label: "الرئيسية", href: "../../pages/Home/index.html" },
        { label: "المنتجات", href: "../../pages/Home/index.html#products" },
        { label: "الأسئلة", href: "../../pages/Home/index.html#faq" },
      ],
    },
    footer: {
      brand: "AI Source Hub",
      version: "ماسح مخاطر المشاريع الناشئة v1.0.0",
    },
    breadcrumbLabel: "مسار الصفحة",
    homeLabel: "الرئيسية",
    homeHref: "../../pages/Home/index.html",
    eyebrow: "التحقق من الأعمال",
    title: metadata.title.ar,
    description: metadata.shortDescription.ar,
    promise: metadata.promise.ar,
    formTitle: "تقييم المخاطر",
    formDescription: "أجب بسرعة. التقديرات كافية، ولا حاجة لأي تفاصيل مالية سرية.",
    buttonLabel: "افحص مخاطر المشروع",
    processing: "جارٍ فحص ملف المخاطر...",
    progressLabel: "تقدم التقييم",
    emptyState: "سيظهر تقرير المخاطر هنا بعد إكمال التقييم.",
    states: {
      idle: "أكمل التقييم لفحص مخاطر المشروع الناشئ.",
      input: "اجعل الإجابات عملية ومبنية على دليل.",
      invalid: "بعض المدخلات المطلوبة تحتاج إلى مراجعة.",
      success: "اكتمل فحص المخاطر.",
      partial: "اكتمل فحص المخاطر مع مستوى ثقة محدود.",
      error: "تعذر إكمال فحص المخاطر. راجع المدخلات.",
      reset: "ابدأ تقييماً جديداً.",
    },
    labels: {
      overallRiskScore: "درجة المخاطر الكلية",
      riskLevel: "مستوى المخاطر",
      executiveSummary: "الملخص التنفيذي",
      riskBreakdown: "تفصيل أبعاد المخاطر",
      topRisks: "أعلى ثلاث مخاطر",
      strongestArea: "أقوى جانب",
      mostDangerousRisk: "أخطر مخاطرة",
      immediateNextAction: "الخطوة الفورية التالية",
      recommendations: "التوصيات المرتبة",
      validationPlan: "خطوات التحقق المقترحة",
      disclaimer: "تنبيه مهم",
      restart: "إعادة التقييم",
      copyReport: "نسخ التقرير",
      downloadReport: "تحميل التقرير",
      originalInputs: "المدخلات الأصلية",
    },
    levels: {
      low: "مخاطر منخفضة",
      moderate: "مخاطر متوسطة",
      high: "مخاطر مرتفعة",
      critical: "مخاطر حرجة",
    },
    priorities: {
      high: "مرتفعة",
      medium: "متوسطة",
      low: "منخفضة",
    },
    disclaimer:
      "هذه النتيجة تقييم مساعد على اتخاذ القرار فقط. ليست نصيحة مالية أو قانونية أو استثمارية أو مهنية، ولا تضمن نجاح المشروع.",
    report: {
      copied: "تم نسخ التقرير.",
      copyFailed: "تعذر النسخ. يمكنك تحديد التقرير ونسخه يدوياً.",
    },
  },
};

export default metadata;

