export const inputSchema = [
  {
    id: "startupStage",
    type: "select",
    label: { en: "Startup Stage", ar: "مرحلة المشروع" },
    placeholder: { en: "Select the current stage", ar: "اختر المرحلة الحالية" },
    helpText: { en: "Choose the closest stage.", ar: "اختر المرحلة الأقرب." },
    required: true,
    options: [
      { value: "idea", label: { en: "Idea only", ar: "فكرة فقط" } },
      { value: "prototype", label: { en: "Prototype or MVP", ar: "نموذج أولي أو نسخة أولى" } },
      { value: "beta", label: { en: "Beta with users", ar: "نسخة تجريبية مع مستخدمين" } },
      { value: "launched", label: { en: "Launched with customers", ar: "تم الإطلاق مع عملاء" } },
      { value: "growth", label: { en: "Early growth", ar: "نمو مبكر" } },
    ],
    validationMessage: { en: "Select the startup stage.", ar: "اختر مرحلة المشروع." },
    direction: "auto",
  },
  {
    id: "problemClarity",
    type: "radio",
    label: { en: "Problem Clarity", ar: "وضوح المشكلة" },
    helpText: { en: "How clearly is the customer problem defined?", ar: "ما مدى وضوح مشكلة العميل؟" },
    required: true,
    options: [
      { value: "unclear", label: { en: "The problem is still unclear", ar: "المشكلة لا تزال غير واضحة" } },
      { value: "general", label: { en: "The problem is described generally", ar: "المشكلة موصوفة بشكل عام" } },
      { value: "specific", label: { en: "The problem is specific", ar: "المشكلة محددة" } },
      { value: "measured", label: { en: "The problem is specific and measured", ar: "المشكلة محددة ومقاسة" } },
    ],
    validationMessage: { en: "Select the problem clarity level.", ar: "اختر مستوى وضوح المشكلة." },
    direction: "auto",
  },
  {
    id: "targetCustomer",
    type: "radio",
    label: { en: "Target Customer Clarity", ar: "وضوح العميل المستهدف" },
    helpText: { en: "How narrow and reachable is the customer segment?", ar: "ما مدى تحديد شريحة العملاء وإمكانية الوصول إليها؟" },
    required: true,
    options: [
      { value: "broad", label: { en: "Broad audience", ar: "جمهور واسع" } },
      { value: "segment", label: { en: "Defined segment", ar: "شريحة محددة" } },
      { value: "niche", label: { en: "Narrow reachable niche", ar: "شريحة ضيقة يمكن الوصول إليها" } },
      { value: "validated", label: { en: "Validated customer profile", ar: "ملف عميل تم التحقق منه" } },
    ],
    validationMessage: { en: "Select the target customer clarity.", ar: "اختر مستوى وضوح العميل المستهدف." },
    direction: "auto",
  },
  {
    id: "demandEvidence",
    type: "select",
    label: { en: "Evidence of Customer Demand", ar: "دليل طلب العملاء" },
    placeholder: { en: "Select the strongest evidence", ar: "اختر أقوى دليل" },
    helpText: { en: "Use the strongest evidence you have today.", ar: "استخدم أقوى دليل لديك حالياً." },
    required: true,
    options: [
      { value: "none", label: { en: "No direct evidence yet", ar: "لا يوجد دليل مباشر بعد" } },
      { value: "conversations", label: { en: "Customer conversations", ar: "محادثات مع العملاء" } },
      { value: "waitlist", label: { en: "Waitlist or signups", ar: "قائمة انتظار أو تسجيلات" } },
      { value: "pilots", label: { en: "Pilots or trials", ar: "تجارب أو مشاريع تجريبية" } },
      { value: "paying", label: { en: "Paying customers", ar: "عملاء يدفعون" } },
    ],
    validationMessage: { en: "Select the demand evidence.", ar: "اختر دليل طلب العملاء." },
    direction: "auto",
  },
  {
    id: "marketAccess",
    type: "select",
    label: { en: "Market Size and Accessibility", ar: "حجم السوق وإمكانية الوصول" },
    placeholder: { en: "Select market access", ar: "اختر إمكانية الوصول للسوق" },
    helpText: { en: "Focus on access, not a large market claim.", ar: "ركّز على إمكانية الوصول وليس حجم السوق فقط." },
    required: true,
    options: [
      { value: "unknown", label: { en: "Market size and access are unknown", ar: "حجم السوق والوصول إليه غير معروفين" } },
      { value: "hard", label: { en: "Large but hard to reach", ar: "كبير لكن الوصول إليه صعب" } },
      { value: "reachable", label: { en: "Reachable first segment", ar: "شريحة أولى يمكن الوصول إليها" } },
      { value: "existing_channel", label: { en: "Existing access channel", ar: "قناة وصول موجودة" } },
    ],
    validationMessage: { en: "Select market accessibility.", ar: "اختر إمكانية الوصول للسوق." },
    direction: "auto",
  },
  {
    id: "competitiveAdvantage",
    type: "select",
    label: { en: "Competitive Advantage", ar: "الميزة التنافسية" },
    placeholder: { en: "Select the advantage level", ar: "اختر مستوى الميزة" },
    helpText: { en: "Choose the most honest current advantage.", ar: "اختر الميزة الحالية الأكثر واقعية." },
    required: true,
    options: [
      { value: "none", label: { en: "No clear advantage", ar: "لا توجد ميزة واضحة" } },
      { value: "feature", label: { en: "A useful feature difference", ar: "اختلاف مفيد في ميزة" } },
      { value: "distribution", label: { en: "Better access or distribution", ar: "وصول أو توزيع أفضل" } },
      { value: "defensible", label: { en: "Defensible advantage", ar: "ميزة قابلة للدفاع عنها" } },
    ],
    validationMessage: { en: "Select the competitive advantage.", ar: "اختر الميزة التنافسية." },
    direction: "auto",
  },
  {
    id: "businessModel",
    type: "radio",
    label: { en: "Business Model Clarity", ar: "وضوح نموذج العمل" },
    helpText: { en: "How clear is the way the startup creates revenue?", ar: "ما مدى وضوح طريقة تحقيق الإيرادات؟" },
    required: true,
    options: [
      { value: "unclear", label: { en: "Revenue model is unclear", ar: "نموذج الإيرادات غير واضح" } },
      { value: "single", label: { en: "One simple model selected", ar: "تم اختيار نموذج بسيط واحد" } },
      { value: "tested", label: { en: "Model tested with customers", ar: "تم اختبار النموذج مع العملاء" } },
      { value: "repeatable", label: { en: "Repeatable revenue pattern", ar: "نمط إيرادات قابل للتكرار" } },
    ],
    validationMessage: { en: "Select business model clarity.", ar: "اختر مستوى وضوح نموذج العمل." },
    direction: "auto",
  },
  {
    id: "pricingEvidence",
    type: "select",
    label: { en: "Pricing and Revenue Assumptions", ar: "افتراضات التسعير والإيرادات" },
    placeholder: { en: "Select pricing evidence", ar: "اختر دليل التسعير" },
    helpText: { en: "Do not enter confidential numbers.", ar: "لا تدخل أرقاماً مالية سرية." },
    required: true,
    options: [
      { value: "guess", label: { en: "Mostly a guess", ar: "مجرد تخمين غالباً" } },
      { value: "competitor", label: { en: "Based on alternatives", ar: "مبني على بدائل موجودة" } },
      { value: "tested", label: { en: "Tested willingness to pay", ar: "تم اختبار الاستعداد للدفع" } },
      { value: "paid", label: { en: "Customers already paid", ar: "دفع العملاء بالفعل" } },
    ],
    validationMessage: { en: "Select pricing evidence.", ar: "اختر دليل التسعير." },
    direction: "auto",
  },
  {
    id: "teamCapability",
    type: "select",
    label: { en: "Founder or Team Capability", ar: "قدرة المؤسس أو الفريق" },
    placeholder: { en: "Select capability level", ar: "اختر مستوى القدرة" },
    helpText: { en: "Assess the ability to build, sell, and operate the first version.", ar: "قيّم القدرة على بناء النسخة الأولى وبيعها وتشغيلها." },
    required: true,
    options: [
      { value: "major_gaps", label: { en: "Major capability gaps", ar: "فجوات كبيرة في القدرة" } },
      { value: "some_gaps", label: { en: "Some important gaps", ar: "بعض الفجوات المهمة" } },
      { value: "capable", label: { en: "Capable for first version", ar: "قادر على تنفيذ النسخة الأولى" } },
      { value: "experienced", label: { en: "Experienced in this market", ar: "خبرة في هذا السوق" } },
    ],
    validationMessage: { en: "Select team capability.", ar: "اختر قدرة الفريق." },
    direction: "auto",
  },
  {
    id: "runwayMonths",
    type: "number",
    label: { en: "Available Financial Runway", ar: "المدة المالية المتاحة" },
    placeholder: { en: "Estimated months, not money amount", ar: "عدد الأشهر التقريبي وليس مبلغاً مالياً" },
    helpText: { en: "Use an approximate number of months. Do not enter financial details.", ar: "استخدم عدداً تقريبياً للأشهر. لا تدخل تفاصيل مالية." },
    required: true,
    minimum: 0,
    maximum: 60,
    validationMessage: { en: "Enter estimated runway in months from 0 to 60.", ar: "أدخل المدة التقريبية بالأشهر من 0 إلى 60." },
    direction: "ltr",
  },
  {
    id: "executionComplexity",
    type: "radio",
    label: { en: "Execution Complexity", ar: "تعقيد التنفيذ" },
    helpText: { en: "How hard is the first usable version?", ar: "ما مدى صعوبة النسخة الأولى القابلة للاستخدام؟" },
    required: true,
    options: [
      { value: "high", label: { en: "Complex build or operations", ar: "بناء أو تشغيل معقد" } },
      { value: "medium", label: { en: "Manageable but not simple", ar: "قابل للإدارة لكنه ليس بسيطاً" } },
      { value: "low", label: { en: "Simple first version", ar: "نسخة أولى بسيطة" } },
    ],
    validationMessage: { en: "Select execution complexity.", ar: "اختر تعقيد التنفيذ." },
    direction: "auto",
  },
  {
    id: "dependencyRisks",
    type: "select",
    label: { en: "Legal, Operational, or Dependency Risks", ar: "المخاطر القانونية أو التشغيلية أو مخاطر الاعتماد" },
    placeholder: { en: "Select dependency risk", ar: "اختر مستوى مخاطر الاعتماد" },
    helpText: { en: "Include regulation, suppliers, platforms, or operational blockers.", ar: "يشمل التنظيم أو الموردين أو المنصات أو العوائق التشغيلية." },
    required: true,
    options: [
      { value: "unresolved", label: { en: "Important unresolved risks", ar: "مخاطر مهمة غير محلولة" } },
      { value: "known", label: { en: "Known risks with rough plan", ar: "مخاطر معروفة وخطة أولية" } },
      { value: "controlled", label: { en: "Risks are controlled", ar: "المخاطر تحت السيطرة" } },
      { value: "minimal", label: { en: "Minimal dependency risk", ar: "مخاطر اعتماد منخفضة" } },
    ],
    validationMessage: { en: "Select dependency risk.", ar: "اختر مستوى مخاطر الاعتماد." },
    direction: "auto",
  },
];

export const outputSchema = [
  { id: "overallRiskScore", type: "score", localized: true, required: true },
  { id: "overallRiskLevel", type: "verdict", localized: true, required: true },
  { id: "dimensionScores", type: "score breakdown", localized: true, required: true },
  { id: "strongestArea", type: "strength", localized: true, required: true },
  { id: "mostDangerousRisk", type: "risk", localized: true, required: true },
  { id: "topPriorityRisks", type: "risks", localized: true, required: true },
  { id: "immediateNextAction", type: "next action", localized: true, required: true },
  { id: "recommendations", type: "recommendations", localized: true, required: true },
  { id: "validationPlan", type: "checklist", localized: true, required: true },
  { id: "disclaimer", type: "disclaimer", localized: true, required: true },
];

export default {
  inputSchema,
  outputSchema,
};

