export const colors = {
  light: {
    background: "#f6f4ef",
    surface: "#ffffff",
    surfaceMuted: "#f8fbf9",
    text: "#1f2523",
    textMuted: "#68716d",
    border: "#d9ded7",
    field: "#fbfcfa",
    primary: "#0f766e",
    primaryStrong: "#0a5d56",
    primarySoft: "#e5f3ef",
    warning: "#b7791f",
    warningSoft: "#fff4dc",
    danger: "#b4233c",
    dangerSoft: "#fde8ed",
    success: "#18794e",
    successSoft: "#e6f4ec",
  },
  dark: {
    background: "#121715",
    surface: "#1b211f",
    surfaceMuted: "#202a27",
    text: "#f2f5f1",
    textMuted: "#a9b3ae",
    border: "#39433f",
    field: "#171d1b",
    primary: "#28b8aa",
    primaryStrong: "#5bd4c8",
    primarySoft: "#123330",
    warning: "#e2a93b",
    warningSoft: "#392a10",
    danger: "#ef6f85",
    dangerSoft: "#3b171f",
    success: "#5ec990",
    successSoft: "#173524",
  },
};

export const semanticColors = {
  verdictPursue: "success",
  verdictImprove: "warning",
  verdictPause: "danger",
  scoreStrong: "success",
  scoreModerate: "primary",
  scoreWeak: "warning",
  scoreCritical: "danger",
};

