export const contentEn = {
  language: "en",
  direction: "ltr",
  header: {
    brand: "AI Source Hub",
    tagline: "Decision engines",
    navigationLabel: "Primary navigation",
    nav: [
      { label: "Home", href: "../../../pages/Home/index.html" },
      { label: "Products", href: "../../../pages/Home/index.html#products" },
      { label: "FAQ", href: "../../../pages/Home/index.html#faq" },
    ],
  },
  footer: {
    brand: "AI Source Hub",
    version: "Business Idea Validator migrated MVP",
  },
  breadcrumbLabel: "Breadcrumb",
  homeLabel: "Home",
  homeHref: "../../../pages/Home/index.html",
  eyebrow: "Business decision engine",
  title: "Business Idea Validator",
  description:
    "Evaluate one business idea, understand the biggest risk, and leave with a practical next action.",
  formTitle: "Your idea",
  buttonLabel: "Validate Idea",
  processing: "Analyzing the idea...",
  fields: {
    businessName: "Business name",
    industry: "Industry",
    targetCustomer: "Target customer",
    problemSolved: "Problem solved",
    currentSolution: "Current solution",
    competitiveAdvantage: "Competitive advantage",
    revenueModel: "Revenue model",
    stage: "Stage",
  },
  stageOptions: {
    idea: "Idea",
    mvp: "MVP",
    launched: "Launched",
  },
  actions: {
    previous: "Previous",
    next: "Next",
    submit: "Validate idea",
    validating: "Validating...",
  },
  states: {
    idle: "Enter the four inputs to validate an idea.",
    input: "Keep answers short and specific.",
    invalid: "Some required inputs need attention.",
    ready: "Ready to analyze.",
    success: "Validation complete.",
    partial: "Validation complete with limited confidence.",
    error: "The validation could not be completed. Please review the inputs.",
    reset: "Start again.",
  },
  labels: {
    status: "Status",
    stepperLabel: "Form steps",
    summary: "Your answers will be reviewed by the existing validator engine.",
    guidance: "Complete the form and review the report once analysis is available.",
    report: "Report",
    reportTitle: "Assessment report",
    overallScore: "Overall score",
    marketPotential: "Market potential",
    executionDifficulty: "Execution difficulty",
    competitionLevel: "Competition level",
    mainRisks: "Main risks",
    keyStrengths: "Key strengths",
    recommendedNextAction: "Recommended next action",
    verdict: "Verdict",
    totalScore: "Total Score",
    scoreBreakdown: "Score Breakdown",
    confidence: "Confidence",
    biggestRisk: "Biggest Risk",
    nextAction: "Practical Next Action",
    improvedIdea: "Improved Idea",
    copyReport: "Copy Report",
    downloadReport: "Download Report",
    startAgain: "Start Again",
    noStrengths: "No strengths yet",
    relatedProducts: "Related Products",
    originalInputs: "Original Inputs",
  },
  steps: ["Context", "Problem & solution", "Positioning & economics"],
  signalValues: {
    high: "High",
    medium: "Medium",
    low: "Low",
    moderate: "Moderate",
  },
  categories: {
    problemClarity: "Problem Clarity",
    customerClarity: "Customer Clarity",
    marketNeed: "Market Need",
    monetizationClarity: "Monetization Clarity",
    feasibility: "Feasibility",
  },
  verdicts: {
    weak: "Weak idea / needs major revision",
    unclear: "Promising but unclear",
    good: "Good idea worth testing",
    strong: "Strong idea with clear potential",
  },
  confidence: {
    low: "Low",
    medium: "Medium",
    high: "High",
  },
  report: {
    copied: "Report copied.",
    copyFailed: "Copy failed. Select and copy the report manually.",
    disclaimer:
      "This result is a decision-support assessment, not a guarantee of market success.",
    sections: {
      executiveSummary: "Executive Summary",
      keyFindings: "Key Findings",
      opportunities: "Opportunities",
      risks: "Risks",
      actionPlan: "Action Plan",
      nextActions: "Next Actions",
    },
  },
  emptyState: "Results will appear here after validation.",
  relatedProductsPlaceholder: "More business decision tools will appear here as they are migrated.",
};

export default contentEn;
