export const contentEn = {
  language: "en",
  direction: "ltr",
  header: {
    brand: "AI Source Hub",
    tagline: "Decision engines",
    navigationLabel: "Primary navigation",
    nav: [
      { label: "Home", href: "../../../pages/Home/index.html" },
      { label: "Products", href: "../../../pages/Home/index.html#products" },
      { label: "FAQ", href: "../../../pages/Home/index.html#faq" },
    ],
  },
  footer: {
    brand: "AI Source Hub",
    version: "Business Idea Validator migrated MVP",
  },
  breadcrumbLabel: "Breadcrumb",
  homeLabel: "Home",
  homeHref: "../../../pages/Home/index.html",
  eyebrow: "Business decision engine",
  title: "Business Idea Validator",
  description:
    "Evaluate one business idea, understand the biggest risk, and leave with a practical next action.",
  formTitle: "Your idea",
  buttonLabel: "Validate Idea",
  processing: "Analyzing the idea...",
  fields: {
    businessName: "Business name",
    ideaDescription: "Describe the business idea briefly",
    industry: "Industry",
    targetCustomer: "Target customer",
    problemSolved: "Problem solved",
    currentSolution: "Current customer workaround",
    competitiveAdvantage: "Competitive advantage",
    revenueModel: "Revenue model",
    stage: "Stage",
  },
  helpText: {
    ideaDescription: "What will the business provide, to whom, and does the service travel to the customer or does the customer visit the business location?",
    problemSolved: "Briefly describe the problem the customer has.",
    currentSolution: "Example: they search manually, ask others, use another service, or do nothing.",
  },
  stageOptions: {
    idea: "Idea",
    mvp: "MVP",
    launched: "Launched",
  },
  actions: {
    previous: "Previous",
    next: "Continue",
    submit: "Validate idea",
    validating: "Validating...",
  },
  states: {
    idle: "Enter the four inputs to validate an idea.",
    input: "Keep answers short and specific.",
    invalid: "Some required inputs need attention.",
    ready: "Ready to analyze.",
    success: "Validation complete.",
    partial: "Validation complete with limited confidence.",
    error: "The validation could not be completed. Please review the inputs.",
    reset: "Start again.",
  },
  labels: {
    status: "Status",
    stepperLabel: "Form steps",
    summary: "Your answers will be reviewed by the existing validator engine.",
    guidance: "Complete the form and review the report once analysis is available.",
    report: "Report",
    reportTitle: "Assessment report",
    overallScore: "Overall score",
    marketPotential: "Market potential",
    executionDifficulty: "Execution difficulty",
    competitionLevel: "Competition level",
    mainRisks: "Main risks",
    keyStrengths: "Key strengths",
    recommendedNextAction: "Recommended next action",
    verdict: "Verdict",
    totalScore: "Total Score",
    scoreBreakdown: "Score Breakdown",
    confidence: "Confidence",
    biggestRisk: "Biggest Risk",
    nextAction: "Practical Next Action",
    improvedIdea: "Improved Idea",
    copyReport: "Copy Report",
    downloadReport: "Download Report",
    startAgain: "Start Again",
    noStrengths: "No strengths yet",
    relatedProducts: "Related Products",
    originalInputs: "Original Inputs",
  },
  steps: ["About You", "Your Idea", "Classification"],
  journey: {
    steps: ["About You", "Your Idea", "Classification"],
    continue: "Continue",
    aboutTitle: "About You",
    ideaTitle: "Your Idea",
    classificationTitle: "Classification",
    classificationWaiting:
      "Complete the idea description, customer, problem, and revenue model first, then AI Source Hub will propose the right classification.",
    required: "This field is required to continue.",
    fields: {
      userExperienceLevel: {
        label: "Which description fits you best?",
        help: "Choose the closest answer. You can change it later.",
        placeholder: "Select your experience level",
        options: [
          ["first_time_beginner", "This is my first business"],
          ["limited_experience", "I have limited experience and I’m evaluating a new idea"],
        ],
      },
      firstProject: {
        label: "Is this your first project?",
        help: "This helps us keep the guidance at the right level.",
        placeholder: "Select answer",
        options: [
          ["yes", "Yes"],
          ["no", "No"],
          ["not_sure", "Not sure"],
        ],
      },
      projectStageIntent: {
        label: "What stage is this project in?",
        help: "Stage and experience are separate.",
        placeholder: "Select project stage",
        options: [
          ["initial_idea", "initial idea"],
          ["researching", "researching"],
          ["preparing_to_launch", "preparing to launch"],
          ["operating", "operating"],
          ["improving", "improving"],
          ["expanding", "expanding"],
        ],
      },
      country: {
        label: "Country",
        help: "A country is enough for now. It affects later research, permits, and cost ranges.",
        placeholder: "Example: Saudi Arabia",
      },
      city: {
        label: "City or region",
        help: "Add it if relevant. You can write 'not selected yet'.",
        placeholder: "Example: Jeddah",
      },
      decisionObjective: {
        label: "What decision do you want help with?",
        help: "For example: start, pause, estimate cost, choose location, or understand risks.",
        placeholder: "Example: know whether to continue before spending money",
      },
    },
  },
  signalValues: {
    high: "High",
    medium: "Medium",
    low: "Low",
    moderate: "Moderate",
  },
  categories: {
    problemClarity: "Problem Clarity",
    customerClarity: "Customer Clarity",
    marketNeed: "Market Need",
    monetizationClarity: "Monetization Clarity",
    feasibility: "Feasibility",
  },
  verdicts: {
    weak: "Weak idea / needs major revision",
    unclear: "Promising but unclear",
    good: "Good idea worth testing",
    strong: "Strong idea with clear potential",
  },
  confidence: {
    low: "Low",
    medium: "Medium",
    high: "High",
  },
  report: {
    copied: "Report copied.",
    copyFailed: "Copy failed. Select and copy the report manually.",
    disclaimer:
      "This result is a decision-support assessment, not a guarantee of market success.",
    sections: {
      executiveSummary: "Executive Summary",
      keyFindings: "Key Findings",
      opportunities: "Opportunities",
      risks: "Risks",
      actionPlan: "Action Plan",
      nextActions: "Next Actions",
    },
  },
  emptyState: "Results will appear here after validation.",
  relatedProductsPlaceholder: "More business decision tools will appear here as they are migrated.",
};

export default contentEn;
