export const contentAr = {
  language: "ar",
  direction: "rtl",
  header: {
    brand: "AI Source Hub",
    tagline: "محركات قرار",
    navigationLabel: "التنقل الرئيسي",
    nav: [
      { label: "الرئيسية", href: "../../../pages/Home/index.html" },
      { label: "المنتجات", href: "../../../pages/Home/index.html#products" },
      { label: "الأسئلة", href: "../../../pages/Home/index.html#faq" },
    ],
  },
  footer: {
    brand: "AI Source Hub",
    version: "النسخة المهاجرة من مقيّم فكرة العمل",
  },
  breadcrumbLabel: "مسار الصفحة",
  homeLabel: "الرئيسية",
  homeHref: "../../../pages/Home/index.html",
  eyebrow: "محرك قرار للأعمال",
  title: "مقيّم فكرة العمل",
  description:
    "قيّم فكرة عمل واحدة، وافهم أكبر مخاطرة، واحصل على خطوة عملية تالية.",
  formTitle: "فكرتك",
  buttonLabel: "قيّم الفكرة",
  processing: "جارٍ تحليل الفكرة...",
  fields: {
    businessName: "اسم العمل",
    ideaDescription: "صف فكرة المشروع باختصار",
    industry: "القطاع",
    targetCustomer: "العميل المستهدف",
    problemSolved: "ما المشكلة التي تريد حلها؟",
    currentSolution: "كيف يحل العميل هذه المشكلة حاليًا؟",
    competitiveAdvantage: "الميزة التنافسية",
    revenueModel: "نموذج الإيرادات",
    stage: "مرحلة المشروع",
  },
  helpText: {
    ideaDescription: "ماذا سيقدم المشروع، ولمن، وهل تأتي الخدمة إلى العميل أم يذهب العميل إلى موقع المشروع؟",
    problemSolved: "صف المشكلة التي يواجهها العميل باختصار.",
    currentSolution: "مثال: يبحث بنفسه، يسأل الآخرين، يستخدم خدمة أخرى، أو لا يفعل شيئًا.",
  },
  stageOptions: {
    idea: "فكرة",
    mvp: "نموذج أولي",
    launched: "مُطلق",
  },
  actions: {
    previous: "السابق",
    next: "متابعة",
    submit: "قيّم الفكرة",
    validating: "جارٍ التقييم...",
  },
  states: {
    idle: "أدخل المعلومات الأربع لتقييم الفكرة.",
    input: "اجعل الإجابات قصيرة ومحددة.",
    invalid: "بعض المدخلات المطلوبة تحتاج إلى مراجعة.",
    ready: "جاهز للتحليل.",
    success: "اكتمل التقييم.",
    partial: "اكتمل التقييم مع مستوى ثقة محدود.",
    error: "تعذر إكمال التقييم. راجع المدخلات.",
    reset: "ابدأ من جديد.",
  },
  labels: {
    status: "الحالة",
    stepperLabel: "خطوات النموذج",
    summary: "ستتم مراجعة إجاباتك باستخدام محرك التقييم الحالي.",
    guidance: "أكمل النموذج ثم راجع التقرير بعد توفر التحليل.",
    report: "التقرير",
    reportTitle: "تقرير التقييم",
    overallScore: "الدرجة الكلية",
    marketPotential: "إمكانات السوق",
    executionDifficulty: "صعوبة التنفيذ",
    competitionLevel: "مستوى المنافسة",
    mainRisks: "المخاطر الرئيسية",
    keyStrengths: "نقاط القوة الرئيسية",
    recommendedNextAction: "الخطوة التالية المقترحة",
    verdict: "القرار",
    totalScore: "الدرجة الكلية",
    scoreBreakdown: "تفصيل الدرجات",
    confidence: "مستوى الثقة",
    biggestRisk: "أكبر مخاطرة",
    nextAction: "الخطوة العملية التالية",
    improvedIdea: "الصياغة المحسّنة للفكرة",
    copyReport: "نسخ التقرير",
    downloadReport: "تحميل التقرير",
    startAgain: "ابدأ من جديد",
    noStrengths: "لا توجد نقاط قوة بعد",
    relatedProducts: "منتجات ذات صلة",
    originalInputs: "المدخلات الأصلية",
  },
  steps: ["سياقك", "فكرتك", "تصنيف المشروع"],
  journey: {
    steps: ["سياقك", "فكرتك", "تصنيف المشروع"],
    continue: "متابعة",
    aboutTitle: "سياقك",
    ideaTitle: "فكرتك",
    classificationTitle: "تصنيف المشروع",
    classificationWaiting:
      "أكمل وصف الفكرة والعميل والمشكلة وطريقة الإيرادات أولاً، ثم سنقترح تصنيفاً مناسباً.",
    required: "هذا الحقل مطلوب للمتابعة.",
    fields: {
      userExperienceLevel: {
        label: "أي وصف يناسبك أكثر؟",
        help: "اختر الوصف الأقرب. يمكنك تغييره لاحقاً.",
        placeholder: "اختر مستوى الخبرة",
        options: [
          ["first_time_beginner", "هذه أول تجربة لي في إنشاء مشروع"],
          ["limited_experience", "لدي خبرة محدودة وأقيّم فكرة جديدة"],
        ],
      },
      firstProject: {
        label: "هل هذا أول مشروع لك؟",
        help: "يساعدنا ذلك على جعل الإرشاد مناسباً لمستوى خبرتك.",
        placeholder: "اختر الإجابة",
        options: [
          ["yes", "نعم"],
          ["no", "لا"],
          ["not_sure", "غير متأكد"],
        ],
      },
      projectStageIntent: {
        label: "في أي مرحلة يوجد المشروع؟",
        help: "المرحلة والخبرة أمران منفصلان.",
        placeholder: "اختر مرحلة المشروع",
        options: [
          ["initial_idea", "فكرة أولية"],
          ["researching", "مرحلة البحث"],
          ["preparing_to_launch", "الاستعداد للإطلاق"],
          ["operating", "مشروع يعمل حاليًا"],
          ["improving", "تطوير مشروع قائم"],
          ["expanding", "التوسع"],
        ],
      },
      country: {
        label: "الدولة",
        help: "يكفي اسم الدولة الآن. سيؤثر ذلك لاحقاً في البحث والتراخيص ونطاقات التكلفة.",
        placeholder: "مثال: السعودية",
      },
      city: {
        label: "المدينة أو المنطقة",
        help: "أضفها إذا كانت مهمة. يمكنك كتابة «لم أحدد بعد».",
        placeholder: "مثال: جدة",
      },
      decisionObjective: {
        label: "ما القرار الذي تريد المساعدة فيه؟",
        help: "مثلاً: أبدأ، أتوقف، أقدّر التكلفة، أختار الموقع، أو أفهم المخاطر.",
        placeholder: "مثال: أعرف هل أستمر قبل أن أصرف مالاً",
      },
    },
  },
  signalValues: {
    high: "مرتفع",
    medium: "متوسط",
    low: "منخفض",
    moderate: "متوسط",
  },
  categories: {
    problemClarity: "وضوح المشكلة",
    customerClarity: "وضوح العميل المستهدف",
    marketNeed: "حاجة السوق",
    monetizationClarity: "وضوح نموذج الإيرادات",
    feasibility: "قابلية التنفيذ",
  },
  verdicts: {
    weak: "فكرة ضعيفة وتحتاج إلى مراجعة كبيرة",
    unclear: "فكرة واعدة لكنها غير واضحة",
    good: "فكرة جيدة تستحق الاختبار",
    strong: "فكرة قوية ذات إمكانات واضحة",
  },
  confidence: {
    low: "منخفض",
    medium: "متوسط",
    high: "مرتفع",
  },
  report: {
    copied: "تم نسخ التقرير.",
    copyFailed: "تعذر النسخ. يمكنك تحديد التقرير ونسخه يدوياً.",
    disclaimer:
      "هذه النتيجة تقييم مساعد على اتخاذ القرار وليست ضماناً لنجاح السوق.",
    sections: {
      executiveSummary: "ملخص تنفيذي",
      keyFindings: "أهم النتائج",
      opportunities: "الفرص",
      risks: "المخاطر",
      actionPlan: "خطة العمل",
      nextActions: "الخطوات التالية",
    },
  },
  emptyState: "ستظهر النتائج هنا بعد التقييم.",
  relatedProductsPlaceholder: "ستظهر هنا أدوات قرار أعمال أخرى بعد ترحيلها إلى المنصة.",
};

export default contentAr;
